### ISSUE TITLE
Discuss about communication channel

### ISSUE THREAD

**Issue by keerthivasan-r** [Kreijstal/diytest#5]
What shall we use for communication - slack or discord?? @Kreijstal

**Comment by Kreijstal** [comment]
I think slack is harder to keep up with than discord, and I'm not sure we have enough members to warrant a discussion channel, in my experience, they tend to collect dust, and if you share something on those channels nobody reads them anyway. What would you rather use?

**Comment by keerthivasan-r** [comment]
ha ha, let us wait for few more members to join us then 🤞

**Comment by keerthivasan-r** [comment]
I don't think this is needed for now
