### ISSUE TITLE
List of Features support in website

### ISSUE THREAD

**Issue by keerthivasan-r** [Kreijstal/diytest#6]
Let us have this thread to discuss the minimum features, that we are going to support in the site

1) User registration
2) User Profile
3) Forgot password
4) Create questions 
5) Create Quiz

etc.

Please add or modify

**Comment by Kreijstal** [comment]
yes, I think we could use a library for this

**Comment by keerthivasan-r** [comment]
Do you have any choice of library in your mind?

**Comment by wigeria** [comment]
4 and 5 will be CRUDs for both questions and quizzes, I believe.

I'm personally thinking that it would be a very good idea to allow users to make "Exams" that they can choose to make public or keep private, with it's own ranking system. That would make it easier for a new user to have a look at what's offered. In that case;
6. CRUD for "Exams"

**Comment by keerthivasan-r** [comment]
Welcome @wigeria , Thanks for your input

**Comment by ariadev79** [comment]
How about taking their skills into account?

**Comment by keerthivasan-r** [comment]
@WeiXinFam I am not able to get you completely. Can you eloborate?

**Comment by keerthivasan-r** [comment]
#8
